provider:
  name: faas
  gateway: http://127.0.0.1:8080

functions:
  of-cloud-dashboard:
    lang: node8-express
    handler: ./of-cloud-dashboard
    image: kenfdev/of-cloud-dashboard:0.9.1
    environment:
      write_debug: true
      base_href: '/function/kenfdev-of-cloud-dashboard/'
      public_url: 'https://ae-gw.team-serverless.xyz'
      # Comment out if not using public pretty-URL
      pretty_url: 'http://user.o6s.io/function'
      query_pretty_url: 'false'
